spring:
  application:
    name: servicio-merch-ordenes
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/db_ticketgol_merchordenes?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8112

logging:
  file:
    name: application.log

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html