spring.application.name=pases_temporada
server.port=8102

<<<<<<< HEAD:ticketgol/pases_temporada_M/src/main/resources/application.properties
spring.datasource.url=jdbc:mysql://localhost:3306/db_ticketgol_pasestemporada
=======
spring.datasource.url=jdbc:mysql://localhost:3306/db_ticketgol_pasestemporada?createDatabaseIfNotExist=true
>>>>>>> main:ticketgol/pases_temporada/src/main/resources/application.properties
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

<<<<<<< HEAD:ticketgol/pases_temporada_M/src/main/resources/application.properties
usuario-service.url=http://localhost/api/v1/usuarios
=======
usuario-service.url=http://localhost:8080/api/v1/usuarios
>>>>>>> main:ticketgol/pases_temporada/src/main/resources/application.properties
